import { useState, useEffect, useCallback, useRef } from "react";

// ── World Cup 2026 knockout bracket ──
// No LLM dependency: real results come from /results.json,
// which is generated by sync-worldcup.mjs (football-data.org).
// Baseline results below keep the bracket usable even before the first sync.

const TEAMS = {
  RSA: { name: "South Africa", flag: "🇿🇦" },
  CAN: { name: "Canada", flag: "🇨🇦" },
  BRA: { name: "Brazil", flag: "🇧🇷" },
  JPN: { name: "Japan", flag: "🇯🇵" },
  GER: { name: "Germany", flag: "🇩🇪" },
  PAR: { name: "Paraguay", flag: "🇵🇾" },
  NED: { name: "Netherlands", flag: "🇳🇱" },
  MAR: { name: "Morocco", flag: "🇲🇦" },
  CIV: { name: "Ivory Coast", flag: "🇨🇮" },
  NOR: { name: "Norway", flag: "🇳🇴" },
  FRA: { name: "France", flag: "🇫🇷" },
  SWE: { name: "Sweden", flag: "🇸🇪" },
  MEX: { name: "Mexico", flag: "🇲🇽" },
  ECU: { name: "Ecuador", flag: "🇪🇨" },
  ENG: { name: "England", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  COD: { name: "DR Congo", flag: "🇨🇩" },
  BEL: { name: "Belgium", flag: "🇧🇪" },
  SEN: { name: "Senegal", flag: "🇸🇳" },
  USA: { name: "USA", flag: "🇺🇸" },
  BIH: { name: "Bosnia & Herz.", flag: "🇧🇦" },
  ESP: { name: "Spain", flag: "🇪🇸" },
  AUT: { name: "Austria", flag: "🇦🇹" },
  POR: { name: "Portugal", flag: "🇵🇹" },
  CRO: { name: "Croatia", flag: "🇭🇷" },
  SUI: { name: "Switzerland", flag: "🇨🇭" },
  ALG: { name: "Algeria", flag: "🇩🇿" },
  AUS: { name: "Australia", flag: "🇦🇺" },
  EGY: { name: "Egypt", flag: "🇪🇬" },
  ARG: { name: "Argentina", flag: "🇦🇷" },
  CPV: { name: "Cape Verde", flag: "🇨🇻" },
  COL: { name: "Colombia", flag: "🇨🇴" },
  GHA: { name: "Ghana", flag: "🇬🇭" },
};

// slots: string = fixed team code, { from: matchId } = winner of that match
const BASE_MATCHES = {
  L1: { slots: ["GER", "PAR"], winner: "PAR", score: "1–1 (3–4 pens)" },
  L2: { slots: ["FRA", "SWE"], winner: "FRA", score: "3–0" },
  L3: { slots: ["CAN", "RSA"], winner: "CAN", score: "1–0" },
  L4: { slots: ["NED", "MAR"], winner: "MAR", score: "1–1 (2–3 pens)" },
  L5: { slots: ["POR", "CRO"], date: "Jul 2" },
  L6: { slots: ["ESP", "AUT"], date: "Jul 2" },
  L7: { slots: ["USA", "BIH"], date: "Jul 1–2" },
  L8: { slots: ["BEL", "SEN"], winner: "BEL", score: "3–2 aet" },
  R1: { slots: ["BRA", "JPN"], winner: "BRA", score: "2–1" },
  R2: { slots: ["CIV", "NOR"], winner: "NOR", score: "1–2" },
  R3: { slots: ["MEX", "ECU"], winner: "MEX", score: "2–0" },
  R4: { slots: ["ENG", "COD"], winner: "ENG", score: "2–1" },
  R5: { slots: ["AUS", "EGY"], date: "Jul 3" },
  R6: { slots: ["ARG", "CPV"], date: "Jul 3" },
  R7: { slots: ["SUI", "ALG"], date: "Jul 2" },
  R8: { slots: ["COL", "GHA"], date: "Jul 3" },
  M89: { slots: [{ from: "L1" }, { from: "L2" }], date: "Jul 4" },
  M90: { slots: [{ from: "L3" }, { from: "L4" }], date: "Jul 4" },
  M93: { slots: [{ from: "L5" }, { from: "L6" }], date: "Jul 6" },
  M94: { slots: [{ from: "L7" }, { from: "L8" }], date: "Jul 6" },
  M91: { slots: [{ from: "R1" }, { from: "R2" }], date: "Jul 5" },
  M92: { slots: [{ from: "R3" }, { from: "R4" }], date: "Jul 5" },
  M95: { slots: [{ from: "R5" }, { from: "R6" }], date: "Jul 7" },
  M96: { slots: [{ from: "R7" }, { from: "R8" }], date: "Jul 7" },
  M97: { slots: [{ from: "M89" }, { from: "M90" }], date: "Jul 9" },
  M98: { slots: [{ from: "M93" }, { from: "M94" }], date: "Jul 10" },
  M99: { slots: [{ from: "M91" }, { from: "M92" }], date: "Jul 10" },
  M100: { slots: [{ from: "M95" }, { from: "M96" }], date: "Jul 11" },
  SF1: { slots: [{ from: "M97" }, { from: "M98" }], date: "Jul 14" },
  SF2: { slots: [{ from: "M99" }, { from: "M100" }], date: "Jul 15" },
  FIN: { slots: [{ from: "SF1" }, { from: "SF2" }], date: "Jul 19 · MetLife" },
};

const COLORS = {
  bg: "#07130b",
  panel: "#0e1d12",
  panelSoft: "#122517",
  line: "#22402b",
  text: "#e8f3e4",
  dim: "#7c937f",
  gold: "#e6c15a",
  goldDeep: "#8a6d1f",
  live: "#8fdcae",
  error: "#e08a8a",
};

const PICKS_KEY = "wc2026-picks";
const BUSTED_KEY = "wc2026-busted";

const loadStored = (key, fallback) => {
  try {
    const parsed = JSON.parse(localStorage.getItem(key));
    return parsed && typeof parsed === "object" ? parsed : fallback;
  } catch {
    return fallback;
  }
};

const roundLabel = (id) =>
  id === "FIN" ? "the Final"
    : id.startsWith("SF") ? "the Semifinal"
    : ["M97", "M98", "M99", "M100"].includes(id) ? "the Quarterfinal"
    : id.startsWith("M") ? "the Round of 16"
    : "the Round of 32";

const teamLabel = (code) => (TEAMS[code] ? `${TEAMS[code].flag} ${TEAMS[code].name}` : code);

export default function WorldCupBracket() {
  const [picks, setPicks] = useState(() => loadStored(PICKS_KEY, {}));
  const [busted, setBusted] = useState(() => {
    const stored = loadStored(BUSTED_KEY, []);
    return Array.isArray(stored) ? stored : [];
  });
  const [restoredCount] = useState(() => Object.keys(loadStored(PICKS_KEY, {})).length);
  const [liveResults, setLiveResults] = useState({});
  const [syncMsg, setSyncMsg] = useState("");

  const realResult = useCallback(
    (id) => {
      const live = liveResults[id];
      if (live && TEAMS[live.winner]) return live;
      const base = BASE_MATCHES[id];
      return base.winner ? { winner: base.winner, score: base.score } : null;
    },
    [liveResults]
  );

  const winnerOf = (id, p = picks) => {
    const real = realResult(id);
    return real ? real.winner : p[id] || null;
  };

  const resolveSlot = (slot, p = picks) =>
    typeof slot === "string" ? slot : winnerOf(slot.from, p);

  // Teams that can STILL win match `id`, considering only real results (not
  // the user's picks). This is how we tell "reality eliminated this team"
  // apart from "this match simply hasn't been decided yet" — an undecided
  // upstream match leaves every team in its subtree reachable.
  const reachableReal = useCallback(
    (id) => {
      const real = realResult(id);
      if (real) return new Set([real.winner]);
      const occupants = (slot) =>
        typeof slot === "string" ? new Set([slot]) : reachableReal(slot.from);
      const m = BASE_MATCHES[id];
      return new Set([...occupants(m.slots[0]), ...occupants(m.slots[1])]);
    },
    [realResult]
  );

  // Drop picks that can no longer stand, given picks + real results. A pick
  // survives if its team can still occupy either slot: a decided slot must
  // equal the team, but an UNDECIDED slot only rules the team out when
  // reality has eliminated it — otherwise the pick waits for that match.
  const cleanPicks = useCallback(
    (p) => {
      const next = { ...p };
      const winnerIn = (id) => {
        const real = realResult(id);
        return real ? real.winner : next[id] || null;
      };
      const canOccupy = (slot, team) => {
        if (typeof slot === "string") return slot === team;
        const w = winnerIn(slot.from);
        return w !== null ? w === team : reachableReal(slot.from).has(team);
      };
      let changed = true;
      while (changed) {
        changed = false;
        for (const [id, m] of Object.entries(BASE_MATCHES)) {
          if (!next[id]) continue;
          if (realResult(id)) { delete next[id]; changed = true; continue; }
          const team = next[id];
          if (!canOccupy(m.slots[0], team) && !canOccupy(m.slots[1], team)) {
            delete next[id]; changed = true;
          }
        }
      }
      return next;
    },
    [realResult, reachableReal]
  );

  const pick = (matchId, team) =>
    setPicks((prev) => cleanPicks({ ...prev, [matchId]: team }));

  // ── Load results.json (generated by sync-worldcup.mjs) ──
  const loadResults = useCallback(async () => {
    try {
      // BASE_URL keeps this working when hosted under a sub-path (GitHub Pages)
      const res = await fetch(`${import.meta.env.BASE_URL}results.json?t=${Date.now()}`); // cache-bust
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const data = await res.json();
      const incoming = data.results || {};
      const valid = {};
      for (const [id, r] of Object.entries(incoming)) {
        if (BASE_MATCHES[id] && r && TEAMS[r.winner]) {
          valid[id] = { winner: r.winner, score: r.score || "FT" };
        }
      }
      setLiveResults(valid);
      setSyncMsg(
        data.updatedAt
          ? `Results synced from ${new Date(data.updatedAt).toLocaleString()}`
          : "Results loaded"
      );
    } catch {
      setSyncMsg("No results.json yet — run `node sync-worldcup.mjs` to generate it. Showing baseline data.");
    }
  }, []);

  // Ask the dev server to pull fresh results from the API, then re-read
  // results.json. On static hosting /api/sync doesn't exist — the catch
  // swallows it and we simply serve the results baked in at deploy time.
  const syncNow = useCallback(async () => {
    try {
      await fetch("/api/sync", { method: "POST" });
    } catch {
      /* no dev server — static hosting */
    }
    await loadResults();
  }, [loadResults]);

  useEffect(() => {
    loadResults(); // show what we have immediately…
    syncNow(); //     …then refresh it from the API
  }, [loadResults, syncNow]);

  // Persist picks and busted-pick notices across visits
  const picksRef = useRef(picks);
  useEffect(() => {
    picksRef.current = picks;
    localStorage.setItem(PICKS_KEY, JSON.stringify(picks));
  }, [picks]);
  useEffect(() => {
    localStorage.setItem(BUSTED_KEY, JSON.stringify(busted));
  }, [busted]);

  // When fresh real results land, drop invalidated picks — and record
  // why each one died, so the user is told instead of it vanishing silently.
  useEffect(() => {
    const prev = picksRef.current;
    const next = cleanPicks(prev);
    const removed = Object.keys(prev).filter((id) => !(id in next));
    if (removed.length === 0) return;
    setBusted((old) => {
      const fresh = [];
      for (const id of removed) {
        const picked = prev[id];
        const real = realResult(id);
        if (real && real.winner === picked) continue; // pick was right — result just locked in
        // Team still alive in reality → this pick was only orphaned by another
        // pick change, not a wrong prediction. Drop it silently.
        if (reachableReal(id).has(picked)) continue;
        const entry = real
          ? { matchId: id, picked, actual: real.winner, score: real.score }
          : { matchId: id, picked };
        const dup = old
          .concat(fresh)
          .some((b) => b.matchId === entry.matchId && b.picked === entry.picked);
        if (!dup) fresh.push(entry);
      }
      return fresh.length ? [...old, ...fresh] : old;
    });
    setPicks(next);
  }, [liveResults, cleanPicks, realResult, reachableReal]);

  // Heal the stored busted list against current reality: drop any notice whose
  // team is actually still alive (false positives left by an earlier version,
  // or a pick that only looked doomed until later results arrived) or that is
  // malformed. A genuine elimination — the team can no longer reach that match
  // — stays. This keeps old browsers from showing stale "knocked out" notices.
  useEffect(() => {
    // Wait until live results are loaded — before that, no team looks
    // eliminated and we'd wrongly prune genuine notices.
    if (Object.keys(liveResults).length === 0) return;
    setBusted((old) => {
      const valid = old.filter(
        (b) => b && BASE_MATCHES[b.matchId] && b.picked && !reachableReal(b.matchId).has(b.picked)
      );
      return valid.length === old.length ? old : valid;
    });
  }, [liveResults, reachableReal]);

  const champion = winnerOf("FIN");
  const totalPickable = Object.keys(BASE_MATCHES).filter((id) => !realResult(id)).length;
  const pickedCount = Object.keys(picks).length;

  const TeamRow = ({ matchId, team, isWinner, decided, locked }) => {
    if (!team)
      return (
        <div style={{ display: "flex", alignItems: "center", gap: 8, padding: "7px 10px", color: COLORS.dim, fontSize: 13, fontStyle: "italic" }}>
          <span style={{ width: 20, textAlign: "center" }}>·</span> TBD
        </div>
      );
    const t = TEAMS[team];
    const dimmed = decided && !isWinner;
    return (
      <div
        onClick={() => !locked && pick(matchId, team)}
        style={{
          display: "flex", alignItems: "center", gap: 8, padding: "7px 10px",
          cursor: locked ? "default" : "pointer",
          background: isWinner ? "rgba(230,193,90,0.12)" : "transparent",
          borderLeft: isWinner ? `3px solid ${COLORS.gold}` : "3px solid transparent",
          opacity: dimmed ? 0.38 : 1,
          transition: "background 120ms, opacity 120ms",
        }}
        onMouseEnter={(e) => { if (!locked && !isWinner) e.currentTarget.style.background = "rgba(143,220,174,0.08)"; }}
        onMouseLeave={(e) => { if (!isWinner) e.currentTarget.style.background = "transparent"; }}
      >
        <span style={{ fontSize: 17, width: 22, textAlign: "center" }}>{t.flag}</span>
        <span style={{
          fontSize: 13, fontWeight: isWinner ? 700 : 500,
          color: isWinner ? COLORS.gold : COLORS.text,
          whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis",
        }}>
          {t.name}
        </span>
      </div>
    );
  };

  const MatchCard = ({ id }) => {
    const m = BASE_MATCHES[id];
    const a = resolveSlot(m.slots[0]);
    const b = resolveSlot(m.slots[1]);
    const real = realResult(id);
    const w = winnerOf(id);
    const canPick = !real && a && b;
    return (
      <div style={{
        background: COLORS.panel,
        border: `1px solid ${w ? COLORS.goldDeep : COLORS.line}`,
        borderRadius: 10, overflow: "hidden", width: 172,
        boxShadow: w ? "0 0 14px rgba(230,193,90,0.10)" : "none",
      }}>
        <TeamRow matchId={id} team={a} isWinner={w && w === a} decided={!!w} locked={!canPick} />
        <div style={{ height: 1, background: COLORS.line }} />
        <TeamRow matchId={id} team={b} isWinner={w && w === b} decided={!!w} locked={!canPick} />
        <div style={{
          padding: "3px 10px", fontSize: 10, letterSpacing: "0.08em", textTransform: "uppercase",
          color: real ? COLORS.dim : canPick ? COLORS.live : COLORS.dim,
          background: COLORS.panelSoft, display: "flex", justifyContent: "space-between",
        }}>
          <span>{real ? "FT" : m.date || ""}</span>
          <span>{real ? real.score : canPick && !w ? "tap to pick" : !real && w ? "your pick" : ""}</span>
        </div>
      </div>
    );
  };

  const Column = ({ title, ids, justify = "space-around" }) => (
    <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
      <div style={{ fontSize: 10, letterSpacing: "0.18em", textTransform: "uppercase", color: COLORS.dim, textAlign: "center", fontWeight: 700 }}>
        {title}
      </div>
      <div style={{ display: "flex", flexDirection: "column", justifyContent: justify, gap: 14, flex: 1 }}>
        {ids.map((id) => <MatchCard key={id} id={id} />)}
      </div>
    </div>
  );

  return (
    <div style={{
      minHeight: "100vh", background: COLORS.bg, color: COLORS.text,
      fontFamily: "'Avenir Next','Segoe UI',system-ui,sans-serif", padding: "24px 12px",
    }}>
      <div style={{ textAlign: "center", marginBottom: 6 }}>
        <div style={{ fontSize: 11, letterSpacing: "0.35em", color: COLORS.gold, fontWeight: 700 }}>
          FIFA WORLD CUP 2026
        </div>
        <h1 style={{ margin: "4px 0 2px", fontSize: 26, fontWeight: 800, letterSpacing: "-0.01em" }}>
          Road to the Final — Prediction Bracket
        </h1>
        <div style={{ fontSize: 12, color: COLORS.dim }}>
          Final results locked in gold · tap teams in undecided matches to predict · {pickedCount}/{totalPickable} picks made
        </div>
      </div>

      {/* Controls */}
      <div style={{ display: "flex", justifyContent: "center", alignItems: "center", gap: 12, margin: "12px 0" }}>
        <button
          onClick={syncNow}
          style={{
            background: "rgba(143,220,174,0.12)", border: `1px solid ${COLORS.live}`, color: COLORS.live,
            borderRadius: 8, padding: "8px 20px", fontSize: 13, fontWeight: 700,
            cursor: "pointer", letterSpacing: "0.04em",
          }}
        >
          ⟳ Sync results
        </button>
        <button
          onClick={() => setPicks({})}
          style={{
            background: "transparent", border: `1px solid ${COLORS.line}`, color: COLORS.dim,
            borderRadius: 8, padding: "8px 18px", fontSize: 12, cursor: "pointer",
          }}
        >
          Reset my picks
        </button>
      </div>
      {syncMsg && (
        <div style={{ textAlign: "center", fontSize: 12, marginBottom: 10, color: syncMsg.startsWith("No results") ? COLORS.error : COLORS.live }}>
          {syncMsg}
        </div>
      )}
      {restoredCount > 0 && (
        <div style={{ textAlign: "center", fontSize: 12, marginBottom: 10, color: COLORS.dim }}>
          ✓ Restored {restoredCount} saved pick{restoredCount === 1 ? "" : "s"} from your last visit
        </div>
      )}

      {/* Busted predictions — reality overruled these picks */}
      {busted.length > 0 && (
        <div style={{ display: "flex", justifyContent: "center", margin: "0 0 16px" }}>
          <div style={{
            background: "rgba(224,138,138,0.08)", border: `1px solid ${COLORS.error}`,
            borderRadius: 10, padding: "12px 20px", maxWidth: 620,
          }}>
            <div style={{ fontSize: 11, fontWeight: 700, color: COLORS.error, letterSpacing: "0.12em", textTransform: "uppercase", marginBottom: 6 }}>
              ⚠️ Reality check — {busted.length === 1 ? "one of your picks didn't survive" : `${busted.length} of your picks didn't survive`}
            </div>
            {busted.map((b, i) => (
              <div key={`${b.matchId}-${b.picked}`} style={{ fontSize: 13, color: COLORS.text, padding: "3px 0" }}>
                {i + 1}. ❌{" "}
                {b.actual ? (
                  <>In {roundLabel(b.matchId)}, you picked <b>{teamLabel(b.picked)}</b> — <b>{teamLabel(b.actual)}</b> won {b.score}. The bracket has been corrected.</>
                ) : (
                  <>You picked <b>{teamLabel(b.picked)}</b> to reach {roundLabel(b.matchId)}, but they were knocked out earlier. Pick removed.</>
                )}
              </div>
            ))}
            <button
              onClick={() => setBusted([])}
              style={{
                marginTop: 8, background: "transparent", border: `1px solid ${COLORS.error}`,
                color: COLORS.error, borderRadius: 6, padding: "4px 14px", fontSize: 11, cursor: "pointer",
              }}
            >
              Got it — dismiss
            </button>
          </div>
        </div>
      )}

      {/* Champion banner */}
      <div style={{ display: "flex", justifyContent: "center", margin: "6px 0 20px" }}>
        <div style={{
          border: `1px solid ${champion ? COLORS.gold : COLORS.line}`,
          background: champion ? "rgba(230,193,90,0.10)" : COLORS.panel,
          borderRadius: 12, padding: "10px 26px", textAlign: "center", minWidth: 220,
          boxShadow: champion ? "0 0 24px rgba(230,193,90,0.18)" : "none",
        }}>
          <div style={{ fontSize: 10, letterSpacing: "0.25em", color: COLORS.dim, textTransform: "uppercase" }}>
            🏆 Your Champion
          </div>
          <div style={{ fontSize: 20, fontWeight: 800, color: champion ? COLORS.gold : COLORS.dim, marginTop: 2 }}>
            {champion ? `${TEAMS[champion].flag} ${TEAMS[champion].name}` : "— complete your bracket —"}
          </div>
        </div>
      </div>

      {/* Bracket — horizontally scrollable */}
      <div style={{ overflowX: "auto", paddingBottom: 12 }}>
        <div style={{ display: "flex", gap: 18, minWidth: 1330, justifyContent: "center", alignItems: "stretch" }}>
          <Column title="Round of 32" ids={["L1", "L2", "L3", "L4", "L5", "L6", "L7", "L8"]} />
          <Column title="Round of 16" ids={["M89", "M90", "M93", "M94"]} />
          <Column title="Quarterfinal" ids={["M97", "M98"]} />
          <Column title="Semis · Final" ids={["SF1", "FIN", "SF2"]} justify="center" />
          <Column title="Quarterfinal" ids={["M99", "M100"]} />
          <Column title="Round of 16" ids={["M91", "M92", "M95", "M96"]} />
          <Column title="Round of 32" ids={["R1", "R2", "R3", "R4", "R5", "R6", "R7", "R8"]} />
        </div>
      </div>

      <div style={{ textAlign: "center", fontSize: 11, color: COLORS.dim, marginTop: 14 }}>
        Made by <span style={{ color: COLORS.gold, fontWeight: 700 }}>Mahmoud Khedr</span> · live results courtesy of football-data.org
      </div>
    </div>
  );
}
